name: Build and Push Astro Frontend to ECR

on:
  workflow_run:
    workflows: ["Build and Push Astro Frontend to ECR"]  # Must match name exactly
    types:
      - completed
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t 253340479653.dkr.ecr.ap-southeast-1.amazonaws.com/cloudsine_takehome/frontend:latest .

      - name: Push Docker image to ECR
        run: |
          docker push 253340479653.dkr.ecr.ap-southeast-1.amazonaws.com/cloudsine_takehome/frontend:latest